### ISSUE TITLE
Fix `UnhandledPromiseRejectionWarning`s

### ISSUE THREAD

**Issue by JulianGro** [JulianGro/gha-artifact-uploader#16]
```
gha_artifact_uploader  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'OK' of undefined
gha_artifact_uploader  |     at /usr/src/app/index.js:399:44
gha_artifact_uploader  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
gha_artifact_uploader  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
gha_artifact_uploader  |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
gha_artifact_uploader  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
gha_artifact_uploader  |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
gha_artifact_uploader  |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
gha_artifact_uploader  |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
gha_artifact_uploader  |     at /usr/src/app/index.js:39:9
gha_artifact_uploader  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
gha_artifact_uploader  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

```
gha_artifact_uploader  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'INTERNAL_SERVER_ERROR' of undefined
gha_artifact_uploader  |     at /usr/src/app/index.js:45:48
gha_artifact_uploader  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
gha_artifact_uploader  |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
gha_artifact_uploader  |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
gha_artifact_uploader  |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
gha_artifact_uploader  |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
gha_artifact_uploader  |     at expressInit (/usr/src/app/node_modules/express/lib/middleware/init.js:40:5)
gha_artifact_uploader  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
gha_artifact_uploader  |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
gha_artifact_uploader  |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
gha_artifact_uploader  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
```

**Comment by JulianGro** [comment]
Fixed in 15258beb2b14478b1182b7bd0a66b06d075880c5
